diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'left_wheel_joint'
  right_wheel : 'right_wheel_joint'

  publish_rate: 10.0
  cmd_vel_timeout: 0.5
  wheel_separation : 0.26
  wheel_radius : 0.1
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # tf
  enable_odom_tf: true
  base_frame_id: body_link
  odom_frame_id: odom
  publish_cmd: true

  pid_gains:
    left_wheel:
      p: 0.1
      i: 1
      d: 0
    right_wheel:
      p: 0.1
      i: 1
      d: 0

  # limits
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           :  1.00 # m/s
      min_velocity           : -1.00 # m/s
      has_acceleration_limits: true
      max_acceleration       :  1.0 # m/s^2
      min_acceleration       : -1.0 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           :  1.5 # rad/s
      min_velocity           : -1.5 # rad/s
      has_acceleration_limits: true
      max_acceleration       :  1.0  # rad/s^2
      min_acceleration       : -1.0 # rad/s^2
